apiVersion: v1
appVersion: "0.15.3"
description: A Helm chart for prometheus cloudwatch-exporter
name: prometheus-cloudwatch-exporter
version: 0.25.0
home: https://github.com/prometheus/cloudwatch_exporter
sources:
- https://github.com/prometheus/cloudwatch_exporter
keywords:
- aws
- cloudwatch
- prometheus
- exporter
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- name: torstenwalter
  email: mail@torstenwalter.de
- name: asherf
  email: asher@asherfoa.com
