version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"

- package-ecosystem: "npm"
  directory: "/contracts/"
  schedule:
    interval: "weekly"
    day: "saturday"

- package-ecosystem: "pip"
  directory: "/scripts/"
  schedule:
    interval: "weekly"
    day: "saturday"
