apiVersion: v2
name: prometheus-memcached-exporter
description: Prometheus exporter for Memcached metrics
type: application
version: 0.1.0
appVersion: "v0.13.0"
home: https://github.com/prometheus/memcached_exporter
sources:
  - https://github.com/prometheus/memcached_exporter
keywords:
  - prometheus
  - memcached
maintainers:
  - name: rsicart
    email: roger.sicart@gmail.com
