apiVersion: v2
name: prometheus-systemd-exporter
description: A Helm chart for prometheus systemd-exporter
type: application
version: 0.1.0
appVersion: "0.6.0"
home: https://github.com/prometheus-community/systemd_exporter
sources:
- https://github.com/prometheus-community/systemd_exporter
maintainers:
- name: capuche2412
  email: aleroux@wiremind.io
