apiVersion: v1
description: Prometheus SNMP Exporter
name: prometheus-snmp-exporter
version: 2.1.0
appVersion: v0.21.0
home: https://github.com/prometheus/snmp_exporter
sources:
  - https://github.com/prometheus/snmp_exporter
keywords:
  - prometheus
  - snmp
  - monitoring
maintainers:
  - name: miouge1
    email: maxime@root314.com
  - name: xiu
    email: github@xiu.io
  - name: walker-tom
    email: walker.thomas.p@gmail.com
