apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-json-exporter.fullname" . }}
data:
  allow-snippet-annotations: "false"
  config.yml: |
  {{ .Values.configuration.config | nindent 4 }}
